Test proxy source service file
GFLCourses6/client pull request #14
Opened 2024-01-16 07:58 UTC by williambrownqqq

2024-01-16 09:42 UTC, Lokankara commented on src/main/resources/json/SingleProxyNetworkConfig.json
> +  "hostname":"proxy1.example.com",
It is better to put this file in the `src\test\resources` directory

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +    @Test
You can use `@ParameterizedTest + @MethodSource` instead of `@Test`.

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +class ProxyConfigHolderTest {
It does not test cases of `Valid, NotNull` coverage.
you can use for validation:
```
    private final ValidatorFactory validatorFactory = Validation.buildDefaultValidatorFactory();
    private final Validator validator = validatorFactory.getValidator();
 ```

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +import static org.junit.jupiter.api.Assertions.*;
avoid using multi-import

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyCredentialsTest.java
> +class ProxyCredentialsTest {
the same situation with `@Size` and `@NotBlank`

    @NotBlank(message = "must not be blank")
    @Size(min = 6, max = 100, message = "must be between {min} and {max} characters")

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyNetworkConfigTest.java
> +import org.springframework.security.core.parameters.P;
Unused import statement

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyCredentialsTest.java
> +    @Test
these test cases can be changed to `@ParameterizedTest`.
you can use the `ProxyCredentialsArgumentsProvider`

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/service/proxy/source/ProxySourceServiceFileTest.java
> +        MockitoAnnotations.initMocks(this);
`initMocks()` is deprecated

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/service/proxy/source/ProxySourceServiceFileTest.java
> +        assertEquals(Collections.singletonList(expectedProxyConfigs), actualProxyConfigs);
`assertEquals()` between objects of inconvertible types 'List<ProxyConfigHolder>' and 'ProxyConfigHolder'

2024-01-16 09:42 UTC, Lokankara commented on src/test/java/com/gfl/client/util/file/FileJsonParserTest.java
> +import static org.junit.jupiter.api.Assertions.*;
FileNotFoundException: class path resource [json/ProxyConfigs.json] cannot be opened because it does not exist

2024-01-16 10:09 UTC, MazurenkoNick requested changes

2024-01-16 10:09 UTC, MazurenkoNick commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +class ProxyConfigHolderTest {
just test the dto's validation

2024-01-22 14:42 UTC, Lokankara approved these changes

2024-01-22 14:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +    @DisplayName("Test validation fails for invalid proxyCredentials")
This test contains only 3 test cases, 
Better use some MethodSource to cover valid and invalid cases based on traceability matrix

```
private static Stream<Object[]> invalidProxyConfigHolder() { }, 
private static Stream<Object[]> validProxyConfigHolder() { }
```

2024-01-22 14:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +                .filter(v -> v.getPropertyPath().toString().equals("proxyCredentials.username")) // Verifies specific violations for username and password using property paths.
Better use vice versa "proxyCredentials.password".equals(v.getPropertyPath().toString())
Is a good practice, especially when dealing with string literals. 
It helps avoid potential NullPointerException if getPropertyPath() returns null and makes the code more robust.

2024-01-22 14:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyCredentialsTest.java
> +    @DisplayName("Test hashCode method for ProxyCredentials object")
If you want to ensure that the hashCode method adheres to its contract, 
you could write a more comprehensive test by checking:

Consistency: Multiple invocations of hashCode on the same object should consistently return the same hash code.
Equality: If two objects are equal (according to the equals method), their hash codes should be the same.

```
@Test
@DisplayName("Test hashCode method for ProxyCredentials object")
void testHashCode() {
    // Consistency: Multiple invocations should return the same hash code
    int firstHashCode = proxyCredentials.hashCode();
    int secondHashCode = proxyCredentials.hashCode();
    assertEquals(firstHashCode, secondHashCode);

    // Equality: If two objects are equal, their hash codes should be the same
    ProxyCredentials equalCredentials = new ProxyCredentials("username", "password");
    assertEquals(proxyCredentials, equalCredentials);
    assertEquals(proxyCredentials.hashCode(), equalCredentials.hashCode());
}
```

2024-01-22 14:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyCredentialsTest.java
> +        ProxyCredentials credentials = new ProxyCredentials("ThisIsAHostnameWithMoreThanFiftyCharactersInThisSentence", "t#9mBc!RvXzP7sHqGjUyLxKvT1iFwOoD2eA3nZ4rY5e6d7u8i9t0yT1o2a3l4l5e6n7g8a9r0p!i@l
if you need to check size 512, 1024? 
you can use "a".repeat(51)

2024-01-22 14:42 UTC, Lokankara commented on src/test/java/com/gfl/client/model/ProxyCredentialsTest.java
> +                    return v.getPropertyPath().toString().equals("password");
Statement lambda can be replaced with expression lambda

2024-01-22 14:42 UTC, Lokankara commented on src/test/java/com/gfl/client/util/file/FileJsonParserTest.java
> +        List<ProxyConfigHolder> actual = fileJsonParser.getAllFromFile(
It test failed: 
`FileNotFoundException: class path resource [json/ProxyConfigs.json] cannot be opened because it does not exist`

2024-01-22 14:59 UTC, williambrownqqq commented on src/test/java/com/gfl/client/model/ProxyConfigHolderTest.java
> +    static Stream<ProxyConfigHolder> getDifferentProxyConfigHolders() {
I'm not sure what you mean, get this straight pls

2024-01-23 17:25 UTC, MazurenkoNick approved these changes

2024-01-23 17:25 UTC, MazurenkoNick commented on src/test/java/com/gfl/client/model/ProxyNetworkConfigTest.java
> +    }
useless test

2024-01-23 17:25 UTC, MazurenkoNick commented on src/test/java/com/gfl/client/model/ProxyNetworkConfigTest.java
> +    }
there's no need to test toString methods

2024-01-23 20:27 UTC, merged